name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Thay đổi tên nhánh nếu bạn đang sử dụng nhánh khác

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # Nhánh trang GitHub Pages
          FOLDER: ./        # Thư mục chứa nội dung trang web
